```{r setup, include=FALSE}
library(mosaic)
ppi <- seq(from = 0, to = 1, by = 1/1000)
```

Question
========

Was passiert in Bezug auf die Likelihood bei konstantem $p=\frac{y}{n}$, wenn die Anzahl der Versuche $n$ steigt?

*Hinweis:* Sie können zum Beantworten der Frage die App <https://fomshinyapps.shinyapps.io/BaBeBi/> nutzen.

Answerlist
----------
* Die Likelihood wandert nach rechts.
* Die Likelihood wandert nach links.
* Die Likelihood wird breiter.
* Die Likelihood wird schmaler.


Solution
========

Je höher $n$ ist, desto geringer ist die Streuung der Likelihood-Funktion.
Damit wird sie bei höherem $n$ schmaler.
Der Modus, also das Maximum der Likelihood-Funktion, hingegen hängt von $p=\frac{y}{n}$ ab und bleibt damit gleich.

```{r, echo=FALSE, fig.cap="", fig.width=4.5, out.width="50%"}
n <- 20
y <- 5
like <- dbinom(y, n, ppi)

# Visualisierung
gf_line(like ~ ppi,
        color= "#CC79A7", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(L(pi)), 
          title = paste0("n = ", n, " und y = " , y)) |>
  gf_vline(xintercept = 0.25)
```

```{r, echo=FALSE, fig.cap="", fig.width=4.5, out.width="50%"}
n <- 200
y <- 50
like <- dbinom(y, n, ppi)

# Visualisierung
gf_line(like ~ ppi,
        color= "#CC79A7", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(L(pi)), 
          title = paste0("n = ", n, " und y = " , y))|>
  gf_vline(xintercept = 0.25)
```

```{r, echo=FALSE, fig.cap="", fig.width=4.5, out.width="50%"}
n <- 2000
y <- 500
like <- dbinom(y, n, ppi)

# Visualisierung
gf_line(like ~ ppi,
        color= "#CC79A7", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(L(pi)), 
          title = paste0("n = ", n, " und y = " , y))|>
  gf_vline(xintercept = 0.25)
```

Answerlist
----------
* Falsch
* Falsch
* Falsch
* Richtig


Meta-information
================
exname: Like 3
extype: schoice
exsolution: 0001
