```{r setup, include=FALSE}
library(mosaic)
ppi <- seq(from = 0, to = 1, by = 1/1000)
```

Question
========

Bei welchen Parametern der Beta-Posteriori-Verteilung ist das 95%-Kredibilitätsintervall am schmalsten?

*Hinweis:* Sie können zum Beantworten der Frage die App <https://fomshinyapps.shinyapps.io/BaBeBi/> nutzen.

Answerlist
----------
* $\alpha_{post}=20,\,\beta_{post}=30$. 
* $\alpha_{post}=30,\,\beta_{post}=20$. 
* Bei beiden gleich.


Solution
========

```{r, echo=FALSE, fig.cap=""}
alpha_post <- 20
beta_post <- 30

# Kredibilitätsintervall
ki <- qbeta(c(0.025, 0.975), alpha_post, beta_post)

# Dichte
d_post <- dbeta(ppi, shape1 = alpha_post, shape2 = beta_post)

# Visualisierung
gf_line(d_post ~ ppi,
         color= "#009E73", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(f(pi)),
          title = paste0("Beta(", alpha_post, ", " , beta_post, ")")) |>
  gf_vline(xintercept = ki)
```

```{r, echo=FALSE, fig.cap=""}
alpha_post <- 30
beta_post <- 20

# Kredibilitätsintervall
ki <- qbeta(c(0.025, 0.975), alpha_post, beta_post)

# Dichte
d_post <- dbeta(ppi, shape1 = alpha_post, shape2 = beta_post)

# Visualisierung
gf_line(d_post ~ ppi,
         color= "#009E73", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(f(pi)),
          title = paste0("Beta(", alpha_post, ", " , beta_post, ")")) |>
  gf_vline(xintercept = ki)
```


Answerlist
----------
* Falsch
* Falsch
* Richtig


Meta-information
================
exname: Post 1
extype: schoice
exsolution: 001
