```{r setup, include=FALSE}
library(mosaic)
ppi <- seq(from = 0, to = 1, by = 1/1000)
```

Question
========

Bei einer Beta-Prior-Verteilung mit $\alpha_{prior}=\beta_{prior}=1$.
Bei welchen Daten ist das 95%-Kredibilitätsintervall am schmalsten?

*Hinweis:* Sie können zum Beantworten der Frage die App <https://fomshinyapps.shinyapps.io/BaBeBi/> nutzen.

Answerlist
----------
* $n=10, y=5$. 
* $n=100, y=50$. 
* Bei beiden gleich.


Solution
========

Es gilt: $\alpha_{post} = \alpha_{prior} + y, \quad \beta_{post} = \beta_{prior} + n - y$.

```{r, echo=FALSE, fig.cap=""}
alpha_post <- 1 + 5
beta_post <- 1 + 10 - 5

# Kredibilitätsintervall
ki <- qbeta(c(0.025, 0.975), alpha_post, beta_post)

# Dichte
d_post <- dbeta(ppi, shape1 = alpha_post, shape2 = beta_post)

# Visualisierung
gf_line(d_post ~ ppi,
         color= "#009E73", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(f(pi)),
          title = paste0("Beta(", alpha_post, ", " , beta_post, ")")) |>
  gf_vline(xintercept = ki)
```

```{r, echo=FALSE, fig.cap=""}
alpha_post <- 1 + 50
beta_post <- 1 + 100 - 50

# Kredibilitätsintervall
ki <- qbeta(c(0.025, 0.975), alpha_post, beta_post)

# Dichte
d_post <- dbeta(ppi, shape1 = alpha_post, shape2 = beta_post)

# Visualisierung
gf_line(d_post ~ ppi,
         color= "#009E73", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(f(pi)),
          title = paste0("Beta(", alpha_post, ", " , beta_post, ")")) |>
  gf_vline(xintercept = ki)
```


Answerlist
----------
* Falsch
* Richtig
* Falsch

Meta-information
================
exname: Post 2
extype: schoice
exsolution: 010
