```{r setup, include=FALSE}
library(mosaic)
ppi <- seq(from = 0, to = 1, by = 1/1000)
```

Question
========

Welche Parameter liegen folgender Beta-Verteilung zugrunde?

*Hinweis:* Sie können zum Beantworten der Frage die App <https://fomshinyapps.shinyapps.io/BaBeBi/> nutzen.

```{r, echo=FALSE, fig.cap="", fig.width=4.5, out.width="50%"}
alpha_prior <- 10
beta_prior <- 5

# Dichte
d_prior <- dbeta(ppi, shape1 = alpha_prior, shape2 = beta_prior)

# Visualisierung
gf_line(d_prior ~ ppi,
         color= "#D55E00", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(f(pi)))
```


Answerlist
----------
* $\alpha_{prior}=10,\,\beta_{prior}=5$. 
* $\alpha_{prior}=5,\,\beta_{prior}=10$. 
* $\alpha_{prior}=7.5,\,\beta_{prior}=7.5$.


Solution
========

$Modus(\pi)=\frac{\alpha-1}{\alpha+\beta-2}>0.5$, also $\alpha>\beta$.

```{r, echo=FALSE, fig.cap="", fig.width=4.5, out.width="50%"}
alpha_prior <- 10
beta_prior <- 5

# Dichte
d_prior <- dbeta(ppi, shape1 = alpha_prior, shape2 = beta_prior)

# Visualisierung
gf_line(d_prior ~ ppi,
         color= "#D55E00", linewidth = 1.2) |>
  gf_labs(x = expression(pi), y = expression(f(pi))) |>
  gf_vline(xintercept = (alpha_prior-1)/(alpha_prior+beta_prior-2))
```


Answerlist
----------
* Richtig
* Falsch
* Falsch


Meta-information
================
exname: Prior 3
extype: schoice
exsolution: 100
