```{r data generation, echo = FALSE, results = "hide"}
library(mosaic)
data(mtcars)
```

Question
========

F체r die vorliegende Stichprobe gilt:

```{r}
erglm <- lm(mpg ~ wt, data = mtcars)
coef(erglm)
```

Also 

$$\hat{\beta}_1 = `r round(coef(erglm),2)[2]`$$.

Wird das zuf채llige Ziehen simuliert (mit Zur체cklegen, *Bootstrapping*) ergibt sich folgendes Ergebnis:

```{r}
# Zufallszahlengenerator setzen
set.seed(1896)
# Bootstrapping
Bootvtlg <- do(1000)* lm(mpg ~ wt, data = resample(mtcars))
# Bootstrap Verteilung
gf_histogram( ~ wt, data = Bootvtlg, center = ~ coef(erglm)[2], nbins = 21)
# Standardfehler (se)
sd( ~ wt, data = Bootvtlg)
```

Welche Aussage stimmt?

Answerlist
----------
* Der Standardfehler $se$ (hier: `r round(sd( ~ wt, data = Bootvtlg),2)`) beschreibt die Streuung von Sch채tzwerten.
* Der Standardfehler $se$ (hier: `r round(sd( ~ wt, data = Bootvtlg),2)`) beschreibt die Streuung von Beobachtungen.

Solution
========

Answerlist
----------
* Richtig
* Falsch


Meta-information
================
exname: Simualtion Bootstrap
extype: schoice
exsolution: 10