```{r data generation, echo = FALSE, results = "hide"}
# Download data:
# download.file(url = "http://web.stanford.edu/class/cs102/datasets/Titanic.csv", destfile = "titanic.csv" )
include_supplement("titanic.csv")
titanic <- read.csv("titanic.csv")
library(mosaic)
```

Question
========

Es soll analysiert werden, wie der Ticketpreis auf der Titanic streut.


```{r}
var(fare ~ 1, data = titanic)
```

*Hinweis*: Statt `var(y ~ 1)`, d. h. Bestimmung der Varianz ohne unabhängige Variable, also durch eine Konstante (`1`), ist auch `var( ~ y)` möglich.

Welche Aussage stimmt?

Answerlist
----------
* Die Standardabweichung (`sd(fare ~ 1, data = titanic)`) wird kleiner sein als die Varianz.
* Die Standardabweichung (`sd(fare ~ 1, data = titanic)`) wird genau so groß sein wie die Varianz.
* Die Standardabweichung (`sd(fare ~ 1, data = titanic)`) wird größer sein als die Varianz.
* Keine Aussage möglich.


Solution
========

Answerlist
----------
* Richtig
* Falsch
* Falsch
* Falsch

Meta-information
================
exname: Titanic Varianz
extype: schoice
exsolution: 1000