```{r data generation, echo = FALSE, results = "hide"}
# Download data:
# download.file(url = "http://web.stanford.edu/class/cs102/datasets/Titanic.csv", destfile = "titanic.csv" )
include_supplement("titanic.csv")
titanic <- read.csv("titanic.csv")
```

Question
========

Sie erhalten das Ergebnis folgender Analyse:

```{r}
tally(class ~ survived, data = titanic, format = "proportion")
```

Wie lautet die Frage, für die die Antwort `r  tally(class ~ survived, data = titanic, format = "proportion")[1,2]` lautet?


Answerlist
----------
* Wie hoch ist der Anteil der Passagiere in der 1. Klasse?
* Wie hoch ist der Anteil der Überlebenden?
* Wie hoch ist der Anteil der Passagiere aus der 1. Klasse unter den Überlebenden?
* Wie hoch ist der Anteil der Überlebenden unter den Passagieren der 1. Klasse?


Solution
========

`class ~ survived` bestimmt den Anteil der Klassen (abhängige Variable) unter den Überlebenden (unabhängige Variable).

Answerlist
----------
* Falsch
* Falsch
* Richtig
* Falsch

Meta-information
================
exname: Titanic Anteilsfrage
extype: schoice
exsolution: 0010