```{r data generation, echo = FALSE, results = "hide"}
library(ggplot2)
library(ggdag)
theme.fom <- theme_classic(22*1.04)
theme.fom <- theme.fom
theme_set(
  theme.fom  
)

co <- data.frame(x=c(0,1,2), y=c(0,1,0), name=c("A", "B", "C"))

DAG_A <- dagify(B ~ A,
                C ~ A + B,
                coords = co) |> 
  ggdag() + 
  geom_dag_point() + 
  geom_dag_text(size = 6) +
  theme_dag_blank() +
  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(12, "pt"), type = "closed"))
```

Question
========

Angenommen es gelte folgende kausale Struktur:

```{r, echo=FALSE, fig.cap="", fig.height=6, fig.width=6, out.width="60%"}
plot(DAG_A)
```

Um den totalen kausalen Effekt von $B$ auf $C$ zu bestimmen: Welches Modell sollte gewählt werden?

Answerlist
----------
* `C ~ B`
* `C ~ B + A`

Solution
========

Es soll der Effekt von $X$ auf $Y$ bestimmt werden. Damit gilt folgendes:

- Chain (Kette) $X\rightarrow Z\rightarrow Y$: Für den *Mediator* $Z$ darf nicht adjustiert werden, da dann der totale Effekt in einen *direkten* Effekt und einen *indirekten* Effekt via $Z$ zerlegt wird und letzterer geblockt wird.
- Fork (Gabel) $X\leftarrow Z\rightarrow Y$: Für den *Confounder* $Z$ muss adjustiert werden, da dieser eine Scheinkorrelation erzeugt (hat). Diese muss kontrolliert werden.
- Inverted Fork (Umgedrehte Gabel) $X\rightarrow Z\leftarrow Y$: Für den *Collider* $Z$ darf nicht adjustiert werden, da eine Aufnahme in das Modell erst eine Scheinkorrelation erzeugen würde.

Eine Adjustierung bedeutet (u.$\,$a.) eine Aufnahme der Variablen in das Modell.

Hier handelt es sich um eine *Fork* (Gabel) $B\leftarrow A\rightarrow C$, daher muss der Confounder $A$ in das Modell aufgenommen werden.


Answerlist
----------
* Falsch
* Richtig


Meta-information
================
exname: Adjustierung 2
extype: schoice
exsolution: 01