```{r data generation, echo = FALSE, results = "hide"}
lp <- .packages()
for(i in 1:length(lp)){
  if(lp[i] == "mosaic"){
    detach(name = package:mosaic, unload = TRUE)
    }
  if(lp[i] == "ggformula"){
    detach(name = package:ggformula, unload = TRUE)
  }
}
library(ggplot2)
library(ggdag)
theme.fom <- theme_classic(22*1.04)
theme.fom <- theme.fom
theme_set(
  theme.fom  
)

co <- data.frame(x=c(0,1,2), y=c(0,1,0), name=c("A", "B", "C"))

DAG_A <- dagify(B ~ A,
                C ~ A + B,
                coords = co) %>% 
  ggdag() + 
  geom_dag_point() + 
  geom_dag_text(size = 6) +
  theme_dag_blank() +
  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(12, "pt"), type = "closed")) +
  ggtitle("Abbildung A")

DAG_B <- dagify(A ~ B,
                C ~ A + B,
                coords = co) %>% 
  ggdag() + 
  geom_dag_point() + 
  geom_dag_text(size = 6) +
  theme_dag_blank() +
  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(12, "pt"), type = "closed")) +
  ggtitle("Abbildung B")

DAG_C <- dagify(B ~ C + A,
                C ~ A,
                coords = co) %>% 
  ggdag() + 
  geom_dag_point() + 
  geom_dag_text(size = 6) +
  theme_dag_blank() +
  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(12, "pt"), type = "closed")) +
  ggtitle("Abbildung C")

DAG_D <- dagify(B ~ C,
                A ~ B + C,
                coords = co) %>% 
  ggdag() + 
  geom_dag_point() + 
  geom_dag_text(size = 6) +
  theme_dag_blank() +
  geom_dag_edges(arrow_directed = grid::arrow(length = grid::unit(12, "pt"), type = "closed")) +
  ggtitle("Abbildung D")
```

Question
========

Angenommen es gelten folgende kausalen Abhängigkeiten:

- $B=f_B(A, U_B)$. Schreibweise als `R`-Formel: `B ~ A`
- $C=f_C(A,B, U_C)$. Schreibweise als `R`-Formel: `C ~ A + B`


Welche Abbildung zeigt das entsprechenden kausale Diagramm?

```{r, echo=FALSE, fig.cap="", fig.width=7.2, fig.asp=1, out.width="80%"}
gridExtra::grid.arrange(DAG_A, DAG_B, DAG_C, DAG_D, nrow = 2)
```


Answerlist
----------
* Abbildung A.
* Abbildung B.
* Abbildung C.
* Abbildung D.
* Keine der Abbildungen.


Solution
========

`B ~ A` bedeutet, $B$ hängt von $A$ ab, also $A\rightarrow B$.
`C ~ A + B` bedeutet, dass $C$ sowohl von $A$ als auch von $B$ abhängt, also $A\rightarrow C \leftarrow B$.

Answerlist
----------
* Richtig
* Falsch
* Falsch
* Falsch
* Falsch

Meta-information
================
exname: SCM
extype: schoice
exsolution: 10000