```{r data generation, echo = FALSE, results = "hide"}
library(mosaic)
# Zufallszahlengenerator setzen
set.seed(1896)
# Bootstrapping
Bootvtlg <- do(1000)* lm(mpg ~ wt, data = resample(mtcars))
```

Question
========

Aus der Bootstrap-Verteilung lässt sich das Konfidenintervall ableiten:

```{r}
ki95 <- qdata( ~ wt, p = c(0.025, 0.975), data = Bootvtlg) |> round(2)
ki95
```

Welche Aussage stimmt im Zusammenhang mit dem Konfidenzintervall?

Answerlist
----------
* Das Intervall von `r ki95[1]` bis `r ki95[2]` zeigt einen plausiblen Wertebereich für eine Beobachtung.
* Das Intervall von `r ki95[1]` bis `r ki95[2]` zeigt einen unplausiblen Wertebereich für eine Beobachtung.
* Das Intervall von `r ki95[1]` bis `r ki95[2]` zeigt einen plausiblen Wertebereich für eine Steigung.
* Das Intervall von `r ki95[1]` bis `r ki95[2]` zeigt einen unplausiblen Wertebereich für eine Steigung.

Solution
========

Das Konfidenzintervall bezieht sich auf die Stichprobenstatistiken, hier die geschätzte Steigung.
Das Bootstrapping simuliert das Ziehen von vielen Stichproben, aus denen jeweils die Stichprobenstatistik berechnet wird.

Da in `qdata()` mit `p = c(0.025, 0.975)` das 2.5%- und das 97.5%-Quantil zurückgegeben wird, liegen 95$\,$% der Stichprobenstatistiken in diesem zentralen Intervall.
Daher überdeckt das Konfidenzintervall mit einer 95%igen Wahrscheinlichkeit eine geschätzte Steigung beim erneuten Re-Sampling der vorliegenden Stichprobe.

Es zeigt damit auch einen plausiblen bzw. mit den Daten kompatiblen Wertebereich für den unbekannten Wert der Steigung in dem Modell der Population.

Answerlist
----------
* Falsch
* Falsch
* Richtig
* Falsch


Meta-information
================
exname: Konfidenzintervall
extype: schoice
exsolution: 0010