```{r data generation, echo = FALSE, results = "hide"}
library(openintro)
library(mosaic)
data(loans_full_schema)
set.seed(1896)
Kredit <- loans_full_schema %>%
  slice_sample(n = 200) %>%
  rename(zins = interest_rate,
         laufzeit = term) %>%
  mutate(h.ausfall = ifelse(num_historical_failed_to_pay>0, "ja", "nein")) %>%
  select(zins, laufzeit,h.ausfall)

```

Question
========

Von einer Peer-to-Peer-Kreditplattform liegen folgende Daten vor (siehe [hier](https://openintrostat.github.io/openintro/reference/loans_full_schema.html)):

- `zins`: Zinssatz in Prozent.
- `laufzeit`: Laufzeit in Monaten.
- `h.ausfall`: Ist in der Vergangenheit schon einmal eine Zahlung ausgefallen (`ja`, `nein`)?

```{r}
# Lineare Modellierung
erglm <- lm(zins ~ laufzeit + h.ausfall, data = Kredit)
# Ergebniszusammenfassung
summary(erglm)
```

Stimmt die Aussage: $\beta_{laufzeit}=0.14650$?

Answerlist
----------
* Ja.
* Nein.


Solution
========

Es gilt nur für diese Stichprobe  $\hat{\beta}_{laufzeit}=0.14650$ (Zeile `laufzeit`, Spalte `Estimate` [Schätzer]).
Über den Wert des Parameters $\beta$ kann keine Aussage getroffen werden.

Answerlist
----------
* Falsch
* Richtig

Meta-information
================
exname: Estimate
extype: schoice
exsolution: 01