```{r data generation, echo = FALSE, results = "hide"}
# Download data:
# download.file(url = "http://web.stanford.edu/class/cs102/datasets/Titanic.csv", destfile = "titanic.csv" )
include_supplement("titanic.csv")
titanic <- read.csv("titanic.csv")
library(mosaic)
```

Question
========

Für die empirische Verteilungsfunktion $F_n(25)$ je Klasse ergibt sich:

```{r}
pdata(age ~ class, q = 25, data = titanic)
```

In welcher Klasse ist der höchste Anteil der über 25-Jährigen?

Answerlist
----------
* In der 1. Klasse.
* In der 2. Klasse.
* In der 3. Klasse.
* Kann mit der gegebenen Information nicht beantwortet werden.


Solution
========

Die empirische Verteilungsfunktion gibt den Anteil der Werte aus, die kleiner dem gegebenen Wert `q` sind.
Der Anteil der bis 25-Jährigen ist in der ersten Klasse am kleinsten und damit der über 25-Jährigen mit `r 1 - pdata(age ~ class, q = 25, data = titanic)[1, 2]` am größten.

Answerlist
----------
* Richtig
* Falsch
* Falsch
* Falsch


Meta-information
================
exname: Titanic Verteilungsfunktion
extype: schoice
exsolution: 1000