```{r data generation, echo = FALSE, results = "hide"}
# Download data:
# download.file(url = "http://web.stanford.edu/class/cs102/datasets/Titanic.csv", destfile = "titanic.csv" )
include_supplement("titanic.csv")
titanic <- read.csv("titanic.csv")
library(mosaic)
```

Question
========

Folgende Ausgabe zeigt die favorisierten Statistiken (`favstats()`) des Ticketpreises:


```{r, fig.cap="", warning=FALSE}
favstats(~ fare, data = titanic)
```

Welche Verteilungsform wird wohl vorliegen?

Answerlist
----------
* Linksschief.
* Symmetrisch.
* Rechtsschief.


Solution
========

Die Abstände vom Minimum (`min`) zu Q1 und von Q1 zum Median sind viel geringer als die vom Median zu Q3 bzw. Q3 zum Maximum (`max`). Die gleiche Menge an Beobachtungen erstreckt sich rechts auf einen viel größeren Wertebereich, was eine rechtsschiefe Verteilung zeigt. Auch liegt eine rechtsschiefe Verteilung häufig vor, wenn der Mittelwert (`mean`) größer als der Median (`median`) ist.

```{r, fig.cap="", warning=FALSE}
gf_histogram( ~ fare, data = titanic)
```

Answerlist
----------
* Falsch.
* Falsch.
* Richtig.


Meta-information
================
exname: Titanic favstats1
extype: schoice
exsolution: 001